---
layout: page
title: "Intervju: Štefan Urankar"
featured-img: intervju
summary: Intervju
categories: slo-post
---

# Intervju: Stefan Urankar

**Od gospoda Kožuha smo izvedeli, da ste delali na računalnikih za telefonske centrale in razvoju le teh.**

Midva z Janezom Kožuhom sva diplomirala na isti dan pri istem profesorju, nisva se pa zaposlila na isti dan. Namreč jaz, ko sem se zaposlil, sem tudi začel diplomo delat, to je bilo prvi dan v poletju 75. Kar se tiče tega slovenskega računalništva kakor ga jaz vidim, je tako, nekje se moramo pozicionirati, en tak mejnik je lahko razvoj mikroprocesorja 72 leta. Intel 8008, potem pri Motoroli 6800 in pri Zialogu Z80, tako, da malo lažje potem časovne mejnike primerjamo. Seveda v teh letih smo v Sloveniji imeli računalnike, bili so na raznih pozicijah, so se uporabljali v poslovne namene, spomnim se, da je bil tudi na fakulteti za elektrotehniko računalnik, se je uporabljal za pedagoške in znanstvene namene, ko sem jaz študiral sem vedel da je ta računalnik. Nas so poučevali samo Fortran.
Računalniki so že kar nekaj časa bili, to so bili večji računalniki, ki so bazirali na jezikih visoke integracije. Kolikor jaz vidim, če se vrnem v tiste čase, vidim kranj kot neko središče, kjer se je na računalništvu malo bolj resno začelo delati, namreč Iskra Kranj je takrat dobila licenco v Belgiji za telefonsko avtomatsko centralo Metakonta 10c

**To se je začelo leta 72?**

Da, okrog 72 leta se je začelo, takrat so šli ljudje gor, da so se spoznali s to centralo in njihova naloga je bila, da prenesejo to tehnologijo v Kranj in da se te centrale potem prenesejo in začnejo proizvajati. Ko sem jaz prišel na začetku 75 leta, je ta prenos že bil izveden, centrale so se že integrirale ter že precej proizvajale in že zelo kmalu se je začelo razmišljati o posodobitvi teh central. Na začetku so bile te postaje krmiljene s 16-bitnimi mini računalniki, ki se je imenoval ITT 2600 in pa 32-bitni ITT 3200, dva računalnika, ki sta bila uporabljena eden za manjše centrale, ter drugi za malo večje centrale.
Naj povem, da tile računalniki so bili tehnološko tako narejeni, to so bila disketna vezja zelo nizke integracije, to je bila logika TTL, tako da v vezju je bilo nekaj vrat, nekaj par bitnih registrov, tako da en tak računalnik je potem zgledal kot cela omara, v tej omari je bila centralna enota, druga omara je bila pomnilnik, notranji pomnilnik, ki je bil takrat še core memory s feritnimi obročki.
Zunanje enote so bile, boben DRAM, potem tračna enota, potem pa luknjane kartice, teleprinter, lan-printer, tiskalnik, ki je bila precej velika zadeva, če pomislimo v primerjavi z danajšnjimi tiskalniki ampak tako je takrat to bilo.
Skratka, kar želim povedati je, da ti računalniki so se uporabili za krmiljenje teh telefonskih central in ti računalniki so se imenovali procesni računalniki. Oni so morali delovati v realnem času. Odzivati so se morali takoj in v odzivu takoj vzpostaviti svojo vlogo in takoj vzpostaviti zvezo, med tem, ko obstajajo računalniki, kjer ni potrebno, da je hitrost tako velika.
Konzola je imela polno lučk za naslove, podatke in še kaj drugega, prekinitve pa tipke. Tukaj si lahko za vsak bit kaj nastavil. Bilo je zelo uporabno, ker je bilo treba velikokrat videti, kaj se dogaja v realnem času, če je prišlo do napake, si moral zadevo na tistem mestu odreagirati in pogledati, nastaviti naslov ali podatek, kjer si pričakoval napako in od tistega trenutka naprej se je program nekam Trace-av, posnel in se je to potem analiziralo.
To so bili te prvi računalniki, in seveda te računalnike, smo dobili v obliki, ki smo jo počasi začeli posodabljati. Core memory je dobil pomnilniško memorijo, profesionalni pomnilnik, to je bil boben, DRAM, počasi je dobil tudi disk, V/I enota je postala cel ta monitor s tipkovnico, kartica ni bila več potrebna, magnetni trakovi so še vedno bili td.
Lahko rečem da se je računalništvo bolj resno začelo s temi računalniki, saj so prodajali takrat tudi PDP računalniki v Elektrotehni Ljubljana, če se prav spomnim, ampak ta PDP računalnik je bil uporabljen v poslovne namene, nismo ga mogli uporabljat za centrale.
Če gremo naprej, tukaj pri nas v Kranju v Iskri, kjer so se te centrale proizvajale, je bila posebna skupina za računalnike in v tej skupini je bila oseba, ki je poznal 16 bitni računalnik, ki je poznal 32 bitni računalnik in vodja te skupine je bil Andrej Uratnik, zagotovo eden prvih, ki se je zelo poglobljeno začel ukvarjati z računalništvom na slovenskem in kar se tiče razvoja ena prvih oseb v industriji.
No jaz sem kot štipendist prišel k Andreju Uratniku in mi je takoj predlagal, da bi začel razmišljati o mikroračunalniku na bazi mikroprocesorja. On je bil kakšne nekaj mesecev pred tem v Ameriki in je nazaj prinesel literaturo v zvezi z intelovim 8080 in predlagal, da naj bi delal diplomo iz tega, čeprav sem študiral tehniko in telekomunikacije sem se odločil za to in je bila potem to tudi moja diploma.
Takrat sem delal diplomo pri profesorju Virantu in s tisto goro literature, ki sem jih dobil od svojega šefa, so me prosili naj skopiram še nekaj kopij zanje in sem z veseljem sprejel to ponudbo.
Tako, da se je pri nas začelo razmišljati za naše centrale. Pri nas je že tekel razvoj naročniške centrale ampak ne na osnovi enega komercialnega mikroprocesorja, da bi bila krmiljena, ampak krmiljena z nekim avtomatom, ki so ga razvijali pri profesorju Virantu. In to je bila naša prva avtomatska centrala s polprevodniškim vezjem. Kot priklopna matrika za telefonsko centralo, ki je pri Metakonti bil readov kontakt, so pri tej naši centrali te tranzistorji polprevodniška matrika. Tako, da ta avtomat lahko štejemo kot nekakšen programirani doma izdelani mikroračunalnik, z disketnimi diski. Seveda se je potem porodila ideja, da bi začeli na osnovi nekega komercialnega mikroprocesorja, naredili mikroračunalnik, ki bi ga uporabili za našo centralo, tam do 100 naročnikov. Hkrati je pa Iskra začela razmišljati, da bi se lotila računalnikov, tako da v nadaljevanju je stvar potekala tako, da sem šel potem k vojakom, v tem času pa se je iskra okrepila z Janezom Kožuhom, v tej skupini je bil tudi še matematik in mislim, da so v tem času, ko sem bil pri vojakih narejen en prototiping board z mikroprocesorjem, ko pa sem prišel od vojakov pa je bila ideja tako zrela, da sem razmišljal o svoji enoti za računalnike. Takrat so povabili mojega šefa Uratnika, da organizira to skupino. Kar nekaj časa smo delali skupaj v istih prostorih, na eni strani mi, ki smo delali za centrale in oni, ki so začeli samo za računalnike. Iskra se je takrat, čeprav so na začetku razmišljali o Intelu, odločili za Motorolo 6800. Seveda to je veljalo potem za vse, ne samo zanje. Ko sem se vrnil z vojske sem moral, ne moral, sem šel za skoraj eno leto v Belgijo, torej tam smo dobili licenco v razvojno skupino, kjer so delali projekt za prenosno signalizacijo številka 6 med Brusljem in pa med Moskvo, ampak na osnovi 16-bitnega bit-sized mikroprogramiranega procesorja. Od prej sem jaz poznal ta 16 bitni mini računalnik pa tudi 32-bitni, predvsem pa tega 16-bitnega v Belgiji pa še ta bit-sized mikroprogramirani računalnik, ki pa je bil narejen na eni plošči, tehnološko je bil že narejen na večji integraciji, bil je sestavljen iz bit-sizev iz mislim, da 4 bit-size procesorjev in mikroprogramiran, torej ukazi so bili mikrokoda. Ko se vrnem, je ideja, da naredimo mikroračunalnik že dovolj zrela. Tako da je bila moja naloga, da se lotim razvoja mikroračunalnika za našo telefonsko centralo. Paralelno je potekal razvoj pod vodstvom Andreja Uratnika, splošnega mikroračunalnika, ki se je kasneje imenoval Iskra Data 1680. To je bil prvi komercialni mikroračunalnik.
To sem še pozabil povedati, ko je Iskra dobila to tehnologijo iz Belgije, je ta 16-bitni računalnik prejel tudi Jožef Štefan, in ta mini računalnik so na inštitutu študirali pod vodstvom dr. Kolbezna. Z njim smo potem tudi sodelovali, na področju tega miniračunalništva in potem kasneje, na področju mikroračunalništva, tako da skupina od Kolbezna so se zelo resno ukvarjali takrat z računalništvom. Če pa pogledamo tukaj skupino, ki so se začeli ukvarjati z razvojem računalnikom, s splošnim računalnikom, ki naj bi bil za poslovne šolske procesne aplikacije itn. Tukaj pa so se povezali z doktor Kodekom, verjetno ga poznate.

**V kakšni meri je imel ta računalnik slovenske dele in v kaki uvožene?**

Integrirana vezja so bila uvožena iz Amerike, takrat je obstajal embargo, tako da vsa kritična vezja, kot so recimo mikroprocesor, je bilo potrebno precej čakanja preden smo ga dobili, potem je bilo potrebnih cel kup potrdil in to se je čakalo. Iskra je bila v svojem času povezana predvsem z Motorolo in nato kasneje z AMI-jem

**Koliko takih računalnikov pa je bilo približno narejenih?**

V tej skupini? Težko bi rekel, to bodo povedali ljudje, ki so sodelovali pri tem. Če želite vam omenim tudi nekaj imen, ki so na začetku tukaj delali, če koga pozabim naj mi bo oproščeno. Tukaj je začel Rogač Marko, ki je postal vodja hardwarske skupine, Janez Kožuh, ki je bil sicer na začetku tukaj, takrat ko sem bil jaz v vojski pri nas, toda potem ko se je ta skupina se je ta priključil, potem Vlado Peterle, mislim, da je to moja generacija vse. No oni so bili na začetku. Mogoče se bom kasneje še koga spomnil.

**To je bilo takrat, ko so združili Gorenje in Iskra delta?**

Ne, gorenje je bila svoja firma, tako kot Iskra svoja firma. Iskra je bila znotraj, takrat je bila taka organizacija, sestavljena iz več Tozdov, mi smo postali TOZD telematika, z računalniki se je formiral TOZD računalniki, Iskra računalniki. Seveda v okviru iskre je bilo cel kup teh Tozdov odvisno od namena, s čim so se ukvarjali. Lahko vam več povem, kako se je zadeva razvijala v zvezi z računalništvom v procesnem delu za telefonske centrale, čeprav mi je znano tudi računalniški ta del, saj smo dosti sodelovali z njimi, a bodo poznali to bolj fantje, ki so bili tam.
Tukaj sem se angažiral pri razvoju hardware-a za mikroračunalnik telefonske centrale, ki je sprva bil namenjen za 100 naročnikov, kasneje se je to preuredilo da je bilo distribuirano z več centralami, ki so med sabo komunicirale. Prvi računalnik je bil sestavljen iz ene plošče, centralna enota iz ene plošče. Doma imam tudi en mikročip na katerem piše Iskra 680, drugače so čipi od Motorole in od Amija. Zakaj je ta od iskre nevem, ali je to že bilo to od mikroelektronike, saj je to njihova oznaka čipov. Rad bi povedal, da mikroračunalnik za telefonske centrale so imele precej hude zahteve kar se tiče zanesljivosti. Te mikroračunalniki so bili, mini računalniki, ki so bili opremljeni s kakovostno kontrolo na naslovnem in podatkovnem vodilu, pa če se prav spomnim, so imeli tudi korekcijo napak. Tako da design prvega mikroračunalnika je bil tak, da ROM za centralo, je bil sestavljen iz ene plošče, ki je bila centralna enota, tam je bilo to vodilo. Potem so bile druge plošče, kje je bil ROM oz. EPROM za program. Pa potem ram, statični ram itd.. Mi smo se zgledovali po 16 in 32 bitnih mikroračunalnikih. Telefonske centrale so imele paritetno kontrolo, to se pravi poleg 8-podatkovnih bitov je bil še en bit dodan, za kvalitetno kontrolo. Na ramu-u pa smo dodali še več bitov, ki so imeli error detection in error correction, to je bil poseben čip s katerim smo ugotovili napako, če je bila ena napaka smo jo ugotovili in jo tudi popravili, če ste bili dve napaki, se je dalo ugotoviti ne pa popraviti. Imele so precej bogat design, zato je zahteval tudi več okoljske logike, tukaj bi še povedal, da cpu ima v osnovi samo dve prekinitvi, ena je bila non-maskable druga pa je bila maskirna prekinitev, to smo razširili NMI (non-maskable interrupt)  na 4 prekinitve, ki smo jih imenovali trapi. IRQ (interrupt request) pa smo razširili na 4 interupte, te smo uporabljali za diagnostiko, za konzolo, ter za ostale prekinitve, to je bilo vse nivojsko orentiarno, najvišjo pariteto je imel trap 0 najnižjo pa interupt. Zdaj, če je nek interupt bil izveden, pa se je pojavil višji, je imel ta prioriteto, tega sam čip nima ograjeno, to je bilo vse narejeno okoljsko. To se je potem ustvarila cela plošča. Kasneje se je dodala še ena konzola, ne vem točno kako se je imenovala, mogoče CSV? S to konzolo smo dodali še en terminal in ta konzola je imela podobno vlogo, kot tista konzola z lučkam, ta konzola je znala tudi slediti programu, ga znala ustaviti program na neki točki, popravek ne ustaviti ampak je znala program posneti v posebno memorijo in potem iz tam nazaj priklicati in iz tam analizirati, dalo se je posneti program v realnem času, tako da ni bilo treba programa, ki je bi v delovanju, ustaviti ampak smo ga ustavili v realnem času, za te procesne računalnike je bilo to zelo pomembno, zato da se je vedelo kako se je ta napaka obnašala v delovanju. Tako je na koncu nastal računalnik, ki je imel kar nekaj plošč

**Katerega leta ste do delali?**

To je bilo, se mi zdi 77 leta, iz vojske sem prišel 76 potem sem šel v Belgijo. To lahko tudi malo povežem, ko je bila ta centrala tukaj v funkciji, se je poleg računalnika delalo še s polprevodniki. Ostali periferni del centrale, ki je tudi imel svoj razvoj, namreč ta krajevni multipleksor se je tudi napredoval v časovni multipleks s pce-mom. Ta zadeva je bila leta 84, to je že sicer dosti kasneje, tudi nagrajena. To je zgleda bilo 84 leta. Tu se je šlo že za večjo centralo. 010 je bila prva za 100 naročnikov, ta pa je bila že večja sestavljena iz večjih modulov, ki so bili povezani. Ta računalnik, se je imenoval TK6800(telekomunikacijski). Na področju računalništva kar se tiče programske opreme, je zahtevalo zelo veliko inženirjev, to je bil obsežen projekt. Na področju hardware manj, takrat ko je Andrej Uratnik šel vodit računalništvo, je to mesto zasedel Janez Stare in nas je bilo okoli 5-6 inženirjev, to je tudi razširilo, kasneje sem to vlogo Stareta tudi sam prevezel, takrat nas je bilo blizu 10.

**Katerega leta ste prevzeli to vlogo?**

Mislim proti koncu 80 leta.

**In ste bili potem vodja hardwarskega oddelka**

Da, za računalniški del razvoja hardware-a

**In ste to potem delali do upokojitve?**

Mi smo v nadaljevanju razvijali 16-bitni računalnik, ta računalnik smo razvijali skupaj z iskra TOZD računalniki, skupaj s temi fanti, namreč mislili smo si računalnik kot računalnik, zakaj ne bi teh stvari združili, zakaj ne bi naredili računalnikih za oboje. Tako da ta razvoj hardware so prevzeli fantje iz računalniškega oddelka, s tem, da smo na začetku zadeve specificirali. specificirali smo lastno vodilo, takrat nekega standardnega vodila ni bilo na vidiku, kasneje pa se je pojavilo VME vodilo, ne vem ste, slišali za to? Na začetku je bilo to vodilo čisto po naših specifikacijah narejeno, žal je ta računalnik prišel le do prototipne faze, saj ga pri nas nismo nikoli implementirali do točke, kjer bi šel v proizvodnjo. Pri nas se je že čutilo da 8-bitni računalnik po zmogljivostih, memorijskih sposobnostih niso več zadoščali. V tistem času se je veliko delalo na tem, da celoten hardware minimiziramo, z namenom nižanja stroškov. Ta računalnik smo minimizirali na eno mogoče dve plošči vse skupaj, prvič zaradi večjih integracij vezij v svetu, drugič pa zaradi tega ker smo določene funkcije odstranili npr. paritetna kontrola oz. error collection, je šlo vse ven, nivojski čipi so postali veliki in konzola ni bila več v taki funkciji in to se je minimiziralo, kar se je potem poznalo seveda pri strojnih stroških in pri ceni produkta, namreč visoke zahteve, ki so bile zmeraj določene zaradi zahtevane visoke zanesljivosti centrale, zaradi katere je prišlo do vseh teh dodatnih kontrol, so končno le popustile, tako da računalnik brez takih dodatnih kontrol je bil sedaj sprejemljiv. Kar se tiče mini računalnikov, ta dva mini računalnika sta se tudi naprej razvijala, memoric core memory je bil posodobljen v polprevodniško memorijo, to je enako, kot sem že prej omenil, potem VI enote so bile posodobljene, od printerjev ni bilo več teleprinterja, to je bil terminal.

**Kakšne tehnologije pa ste uporabljali pri programiranju?**

Tukaj je bil operacijski sistem, kot se spomnim neka verzija DOS-a, ki je bil poimenovan Iskra DOS, programerski jezik pa je mogoče bil tukaj Basic, pa kakšen Pascal bi lahko še bil.

**Kakšen je bil življenski cikel teh naprav, danes so po dveh letih že zastarele, kako pa včasih?**

Ta 8-bitni je razmeroma dolgo živel, dolgo se je to tudi prodajalo. Mogoče ker je bil čas tak. Ta hardware je bil bombardiran skozi večjo integracijo vezij, se je ves čas posodabljal in postajal manjši, tako da se je ta 8-bitno razmeroma dolgo uporabljal. Tako dolgo, da kljub temu da smo imeli 16-bitni računalnik razvit in pripravljen z namenom, da zamenjamo 8-bitnega, do tega ni prišlo, ker je bilo že prej aktualno nekaj 32-bitnega, tako dolgo se je to proizvajalo. Centrale z 8-bitnim računalnikom so se prodajale ogromno po Rusiji, verjetno še kje v Turčiji. Seveda po Sloveniji in Jugoslaviji, a največ pa v Rusiji, in to zelo dolgo. Kaj vse smo počeli s tem 8-bitnim računalnikom? Razširili smo memorijo, te je zmanjkalo za program in podatke, to je bilo omejeno s procesorjevim 16-bitnim naslovnim poljem, ki je omejeno na 64kb. Kaj smo naredili, ta moj razvoj, ki sem ga naredil in tudi prejel nagrado. Če pogledamo bolje, en ukaz je sestavljen iz več ciklov, cpu komunicira z memorijo, ti cikli pa so odvisni, število ciklov je odvisno od ukaza. Bili so ukazi, ki so imeli samo cikel, ki je bil pri 1 mhz procesorju 1 ms, v tem času se je izvedla ena operacija in prva operacija je bila branje operacijske kode, to je bila samo 1 operacijska koda, lahko je imel ukaz operacijsko kodo in potem še naslavljanje, lahko je bilo treba prebrati 3x iz memorije, 3 cikle od 1 do 3 in temu se je reklo program, lahko je bilo potem nekaj praznih ciklov, kjer je procesor nekaj obdeloval, na koncu je pa npr. izvedel 2 podatkovna prenosa, ali pa odvisno od ukaza, če je bil to shranjevanje ali nalaganje potem je bilo to konec. Lahko pa so bili ukazi, ki so imeli nekaj praznih ciklov, in so bili ukazi, ki so bili sestavljeni od 3 pa do 12 ciklov, mislim, da je bil 12 ciklov najdaljši. Moja ideja kako razširiti memorijo, je bila da ločimo programski del in podatkovni, če je bilo prej vse to skupaj je bilo zdaj narjeno tako, da tukaj je bil program, podatki pa so bili na drugem mestu in to na tak način da smo 16 bitov addresnega polja razširili na 17 bitov. 17 bit se je odločal med tem ali so to podatki ali ne. Kako je prišlo do tega 17 bita, hardware je zunaj zelo hitro prepoznal ali je operacijska koda in vse tisto, kar spada pod program to, za vsak ukaz posebej je bilo treba analizirati cikle in ko je bil program, se je postavil ustrezno ta 17 bit, če je bil podatek, se je tudi ustrezno postavil, npr. za program se je nastavila 1 za podatke pa 0, in to je bilo v hardware-u zelo hitro. Najprej se je dekodiralo brez da bi program kaj delal, vse se je naredilo strojno in ne da bi bilo treba kaj pripravljati, in s tem smo prišli na 128 kB.

**To ste v katerem računalniku naredili?**

v Iskra data 1680

**To je bilo že v prvem modelu ali kasneje potem tudi?**

To je bilo vse naprej od trenutka, ko je bilo to testirano, mene je zelo skrbelo to, ali se bo kje kaj zalomilo, namreč jaz sem tudi prekinitve programiral, ker treba je bilo tudi prekinitve prepoznati in narediti obnovitev itd.. Bila je nevarnost, da bi se kaj zmotil, strah je bil tudi pred tem da dobimo druge procesorje, ki se drugače obnašajo, a nikjer ni prišlo do napake. Take računalnik so delali po Rusiji, pa tudi drugje.
Potem tudi to še ni bilo dovolj, zmanjkalo je, mi bi potrebivaku še za zbirnega, a kljub temu smo še naprej uporabljali kljub pomankljivosti. Zdaj izkušnje iz miniračunalnikov teh ITT-jevih od Della so bile take, oni so imeli že implementirani backswitching, priklop banke, imeli so miljon skomin, ampak so imeli več memorijskih bank in so jih preklapljal, samo to je bila naloga origransje iorene, kar je bilo treba seveda sprogramirati, tako da teh 128 je bilo dodatnih, pa še naslednja banka in naslednja banka in se je dodal še te programski backswitching, tako da se ni več razširjevalo, problem je ostal samo v tem, da je bilo treba v programski opremi predvideti medtem, ko je bilo to narejeno v hardwaru. To se nič nikjer vedelo, program ni vede,l niti ni bilo treba misliti ne programerju.

**Kako so bili te računalniki v primerjavi s konkurenčnimi, po ceni, zmogljivosti?**

Če pogledam v tisti čas, kako je bilo stanje takrat. Tesla v Zagrebu, imela je zgolj licenco od Erriksona, jaz se ne spomnim, da bi oni kake svoje razvoje delali, to je bil čisto naš razvoj poleg licence, tudi neki poskusi so bili v Srbiji, mislim, da v Nišu in Beogradu, a ni bilo primerljivo, vzhod tega ni delal, Rusi niso delali, ampak so kupovali od nas, prišli so k nam in poslali operatorje centrale k nam na izobraževanje, oni niso imeli te tehnologije, takrat je bil postavljen embargo. Sam se spomnim, ko smo za te stvari uporabljali tudi analizatorje, to je bilo tudi težko dobiti. Slišal sem za Madžare, kako so analizator uporabljali, oni so kupili analizator in ga imeli na Dunaju, kjer so ga morali tudi uporabljali, saj ga niso mogli uvoziti.

**Vi ste pa imeli svojega?**

Da, ko smo z opremo začeli moram še omeniti, da na začetku se je programska oprema razvijala na razvojnem sistemu, ki je bil tudi kupljen in sicer je bil prvi razvojni sistem od Amija, to je bilo zelo zgodaj ko se je programirala prva centrala, nekje je bilo treba to programirati. Cross compilerjev na več različnih postajah takrat še nismo imeli, če pogledate tale sistem VIVI, zgoraj desno piše AMI. Imel je samo floopy disk, ni imel nobenega diska 0, operacijski sistem je bil na disketi, tukaj pa prevajalnik, ko so razvijal, seveda moram povedati, da programi v telefonski centrali so se razvijali v assemblerju. Programi so morali biti zelo optimalni in to se je dalo doseči z assemblerjem. Programerji so si pomagali takrat z macroji, tako da čisto vsega ni bilo potrebno narediti v assemblerju, saj so že kar macroje lahko uporabili. To so bili začetki na takem razvojnem sistemu, to je bil od ami-ja razvojni sistem.

**Ste ko se je enkrat računalniški del Iskre, kot sem jaz razumela, združila s tremi podjetji v Iskra delto, uporabljali kaj njihovih računalnikov, ali ste imeli lasten razvoj?**

Mi smo imeli svoje računalnike, mi smo imeli HP računalnike za razvoj, Metaconta del so tako ali tako razvijali na teh njihovih računalnikih, bili so popolnoma samozadostni, oni so imeli tam svojo opremo in svoj software, razvijali so v assemblerju, imeli pa so še neki višji nivojski jezik, pa še par stvari so tam počeli, imeli so tudi simulacijo centrale, na večjem računalniku ITT 3200. Tako so pa preizkušali nove programe, da ni bilo potrebno imeti žive centrale, žive makete, ampak so lahko uporabljali simulator, ki je bil v tem večjem računalniku. Tako da so programe preizkušali kar na tem simulatorju. Verjetno so te stvari dobili iz Belgije. Tako da to je to. Kaj sem hotel ob vsem tem razvoju še povedat je, da v tem času disk še ni bil aktualen niti zrel. Na Metaconti, se je uporabljal DRAM, bil je zelo zanesljiv, dovolj velik pomnilnik, po slovensko se mu je reklo boben. V svetu se je v tistem času pojavila tehnologija mehurških pomnilnikov, bubble memory in mi smo se na neki točki izmislili da bi naredili zamenjavo za boben, da bi naredili mehurški pomnilnik in naloga v sodelovanju z dr. Kolbeznom smo tudi izpeljali. Tako da je ta zadeva zaživela, vendar nismo nikoli tega uporabili, saj kar naenkrat mehurčni pomnilnik v svetu ni bil aktualen, zakaj je do tega prišlo, ne vem ali je bila to cena ali kaj drugega, ampak je bil ta pomnilnik po realizaciji in strukturni zelo podoben bobnu, ta mehurčni pomnilnik, ki smo ga mi razvijali, naj bi šel v kontainer, ampak na koncu ni šel.

**To je torej produkt iskre?**

Odgovor: Tako, to je slovenski produkt, mi smo hoteli ta bubble memmory imet, zakaj ga potem nismo uporabljali? Na svetu je potem zadeva, kar potihnila in zato se tega ni več omenjalo.

**Koliko takih plošč pa je bilo narejenih**

Samo dve.

**To je še kdo v Sloveniji naredil?**

Ne, tega sigurno ne. Prvič zaradi tega, ker ta želja po novem memmoryu ni dolgo trajala, polega tega pa ni bilo potrebe po tem. Mi smo hoteli ta mehanski zunanji spomin zamenjati za nekaj, kar bi bilo bolj elektronsko, bolj shranjeno stanje, to je bil mehurčni pomnilnik.

**Glede na to da sta bila narejena samo dva, ste vseeno na njih kaj poskušali?**

Da. Samo testiranja je delalo. Ni bilo potem več želje, da bi to uporabili za proizvodnjo. Ne znam več povedati zakaj, eno je bilo verjetno to da v svetu zadeva umre, ker se ni več slišalo o tem, kar naenkrat je zamrlo, ali je bila za to kriva cena ali kaj drugega, ne vem, mogoče je bila tehnologija prezahtevna za razvoj.

**In kako je bilo z razvojem nove tehnologije, ste kdaj zgrešili trg, mogoče tehnologija ni delovala pravilno, se je to dostikrat zgodilo?**

Če vzamem za primer mehurčni pomnilnik, na začetku je to dobro kazal, zelo dobro, mi nismo vedeli takrat kako se bo to odvilo kasneje, nam je ideja bila zelo zanimiva, kot zamenjava za pomnilnik. Te stvari se dogajajo pri razvoju. Poglejte 16-bitni procesor smo razvijal v dobri veri, da zamenjamo 8-bitnega. Mi smo ga naredili, zaradi procesne moči, pa ga nismo uporabili, bil je razvit in ne uporabljen v proizvodnji, smo 8-bitnega delali do nezavesti. Tako da smo potem 32- bitni procesor začeli razvijati, ker so te firme, kot so Intel in druge hitro šle s tehnologijo naprej, seveda ne z isto hitrostjo kot danes.

**Kaj ste pa potem še kaj razvijali, koliko računalnikov ste v bisvtu vi razvili za lastne potrebe?**

8-bitnega sem zelo veliko sam razvijal, od spominskih plošč do konzole, do centralne enote, potem sem za mini računalnik ITT-jev razvijal krmilnik, pa mislim da sem tudi pri memoriji, tega se ne spomnim več. Pri 16-bitnem smo pa sodelovali z Iskra delto, mi smo specificirali posamezne enote, specificirali smo bus, s tem da so oni ta design postavili na VMI ploščo, mi pa na našo standardno ploščo, imeli smo svoj format plošče ki smo ga podedovali od metaconta, to je ta format plošče, ki sem vam ga pokazal, vmi je bil malo drugačen, malo višji in malo krajši. Kasetno enoto implementirali, to je bil magnetni trak, za te mikroračunalnike.

**In kaj se je snemalo na te kasete?**

Ves software, ki se je naredil za te centrale, je bil tukaj gor.

**In to je bilo bolj kot ne programirano v assemblerju?**

DA. Kasneje pa so že kaj v čem drugem, zdaj ne vem mogoče že kaj v C-ju. Vem, da v tistem času je bil zelo popularen potem CHILL (CCITT High Level Language), ne vem no če so v njem kaj delali, to je bil poseben jezik za komunikacijske sisteme, gotovo so pa z macroji že delali.

**In vi ste potem v ves čas, ko ste bili zaposleni, bili na hardware-u, do svoje upokojitve?**

Ne, nisem bil ves čas na hardwareu. Aha še en projekt smo potem delali ko sem bil tam, mi smo naredili X-25 stikalo, to je bila škatla z večjimi porti, bazirana na 32-bitnem procesorju, bila je ena plošča in komunikacijski kanali, ki so bili realizirani z raznimi interfaci, ki si jih menjaval, samo se mi zdi da ta zadeva tudi ni dolgo živela. Tukaj je bila huda konkurenca in cel kup drugih produktov in tako naprej. To je bila tudi ena taka, ena postaja kjer smo nekaj takega razvijali.

**Ste pa ko ste bili zaposleni tam, bili hardwersko samooskrbni, torej delali hardware zase, pa še za zunanje naročnike.**

Seveda, kupiti pa smo morali čipe in enote, v glavnem pa smo računalnike delali sami.

**S temi računalniki ste oskrbovali tudi kakšen drug oddelek, ali so bili specializirani za oddelek telekomunikacij?**

To so bili namenski računalniki, bili so izključno narejeni za naše centrale, res da smo imeli vmes eno idejo da bi na naš 16 bitni računalnik, ki smo ga razvili naložili Unix, in to se je tudi zgodilo, ideja je bila, da bi ga uporabili še za kaj drugega, kot npr. za razvojni sistem, tako da potem smo ga vgradili v eno mizo, popolnoma enak računalnik, saj računalnik kot računalnik. Ta je bil z Unixom in naj bi ga uporabili kot razvojna postaja Unix. Ampak na koncu so prevladali kompletni računalniki, tako da dokakšne množične uporabe tega ni prišlo, je pa ta računalnik se mi zdi tudi v gimnaziji Kranj. Tako da smo imeli tudi opravka z enim Unixom, čeprav Unixa za samo centralo nismo rabili, mi smo ga uporabljali kot razvojno postajo, verjetno so ga imeli tudi tam na hp-ju. Kar se mene tiče jaz sem pol življenja delal na razvoju hardware, kasneje pa sem se začel ukvarjati s konformančnimi testiranji komunikacijskih protokolov. To so pa, protokoli ki jih je kar nekaj v telekomunikacijah, kasneje so se pridružili tudi računalniški protokoli.

**Prej ste omenili embargo, vas je ta kaj omejeval pri razvoju, mogoče ste hoteli kaj uvoziti pa niste mogli, ker Američani takrat niso smeli izvažati v Kitajsko, Rusijo, saj Jugoslavija je imela nek dogovor, samo niste smeli naprej prodajati.**

Ne morali smo pridobiti end-user certifikate, nismo smeli nikamor izvažati ta razvojni sistem, niti pripelati le začasno, vem pa da na vzhodu ga niso morali kupit, imeli smo zgleda neke poti da smo lahko do tega prišli. Posebno za recimo te analizatorje, so bili TOS kodirani analizatorji, ki smo jih uporabili za testiranje protokolov, imeli smo analizatorje od firme Tekelek, od Siemensa. Od Tekeleka smo imel kar 3 analizatorje. to so analizatorji za testiranje protokolov, zdaj, da ne omenjam hardwarske analizatorje, tam se mi zdi da je bilo malo lažje. No kasneje se je to odprlo, embargo pa je nekako zbledel, smo kupovali najsodobnejšo ameriško tehnologijo kar se je tičalo analizatorjev od firme Spyrent in še kakšne druge, ki se jih ta trenutek ne spomnem.

**Vidim, da imate na računalniku en ekran gorenje iskra delta, to je nastalo, takrat ko je bila že iskra delta in je bil združeno ime?**

Prej ste me vprašali Iskra Delta, jaz se spomnim takole, Iskra računalnik je nastal v Kranju, to je bil lasten razvoj na bazi tega mikroprocesorja, pozabil sem še povedati, da te družini 6800 mikroračunalnikov so imeli tudi en mikroračunalnik ki je bil na bazi Ziolaga. Z80 ta ni bil razvit v Sloveniji, v tej skupini, ampak v Nemčiji, to je bila skupina slovencov ki so gor delali in so za Iskro naredili en podoben razvojni sistem, in mislim da se je imenoval ID80, to je bilo v okviru Iskre, potem v Ljubljani je bila Elektrotehna, ki je imela ameriški sistem in ta Elektrotehna, ki se je kasneje imenovala delta, ta del se je združil z Iskra računalniki, slovensko računalništvo se je združilo in se je potem imenovalo Iskra Delta, tako da so delali dvoje sorte računalnikov, lasten razvoj na osnovi mikroprocesorjev, in pa njihov računalnik, ki so ga že prej prodajali.

**Kdaj je pa gorenje prišlo zraven?**

Gorenje, je tudi jaz točno ne vem. Gorenje je npr. s temi terminali sodeloval, to je bilo v gorenju narejeno, gorenje delta, ker verjetno oni so bili za televizorje in jim je to zgleda prav prišlo.

**Iskra Delta je zelo hitro propadla, kako se je takrat gledalo na to, kaj se je javno vedelo, javno reklo da so razlogi za to.**

Tukaj je verjetno več interpretacij, dokler je v prejšnjem sistemu so se te stvari prodajale tako, da verjetno drugi tujci niso mogli prodajati, da je imela iskra delta pravico kot Jugoslovanski prodajati po Jugoslaviji, ko se je tudi ta zadeva spustila so nastali problemi, ne vem katero leto so bili to, ampak poleg tega v tistem času so osebni računalniki močno napredovali in to se je začelo delo vsepovsod in cene so hitro padale, in je bilo težko konkurirati. Z začetka se je verjetno slišalo, te stvari so se zelo tihotapile in kasneje, ko so se začele prodajati, si lahko mislite kaj se je začelo dogajati.

------

- [Nazaj na intervjuje]({{site.base}}/SloRaDe/intervjuji)
